# ML Customization Training Configuration

# Dataset Configuration
dataset:
  fs: 50  # Sampling frequency (Hz)
  window_size_seconds: 60  # Window size in seconds
  window_stride_seconds: 60  # Window stride in seconds
  labeling: "andrew smoking labels"  # Label type to use
  test_size: 0.2  # Train/test split ratio

# Sensor Configuration
sensors:
  use_accelerometer: true   # Include accelerometer data (accel_x, accel_y, accel_z)
  use_gyroscope: true       # Include gyroscope data (gyro_x, gyro_y, gyro_z)

# Model Configuration
model: {}  # Parameters computed automatically from dataset config

# Training Hyperparameters
training:
  batch_size: 512
  learning_rate: 0.0003  # 3e-4
  weight_decay: 0.0001   # 1e-4
  num_epochs: 5000
  
  # Customization training parameters
  base_patience: 20      # Early stopping patience for base training phase
  custom_patience: 20    # Early stopping patience for customization phase
  custom_learning_rate: 0.0003  # Lower LR for fine-tuning (10x lower than base)
  
# Participants Configuration
participants:
  - "tonmoy"
  - "asfik"
  - "ejaz"

# Visualization Configuration
visualization:
  ma_window_size: 5  # Moving average window size for plots
  save_plots: true
  plot_format: "jpg"
  dpi: 300