dataset:
  name: "004_10s_window"
  fs: 50
  window_size_seconds: 10
  window_stride_seconds: 10

training:
  mode: "target_only"
  early_stopping:
    use_early_stopping: true
    patience: 50
    metric: "val_loss"
    
  batch_size: 512
  target_participant: "tonmoy"
  lr: 3e-4
  lr_scheduler:
    use_scheduler: true
    patience: 25

participants:
  - "tonmoy"

visualization:
  plotting_frequency_epochs: 5
  ma_window_size: 5
  save_plots: true
  plot_format: "jpg"
  dpi: 300